server:
  port: 7201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: hello-service-consumer

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

logging:
  config: classpath:logback.xml
